# Generated by Django 2.2.6 on 2020-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=40, null=True)),
                ('time_field', models.CharField(max_length=40, null=True)),
                ('start_time1', models.DateTimeField()),
                ('end_time1', models.DateTimeField()),
                ('start_time2', models.DateTimeField()),
                ('end_time2', models.DateTimeField()),
                ('start_time3', models.DateTimeField()),
                ('end_time3', models.DateTimeField()),
                ('created_ip', models.CharField(max_length=40)),
            ],
        ),
    ]
