# Generated by Django 2.2.6 on 2020-06-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useractivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserActivity',
        ),
    ]
