# Generated by Django 2.2.6 on 2020-06-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useractivity', '0004_auto_20200604_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='created_ip',
        ),
    ]
